In [ ]:
 # Load All Packages #

import os
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive

# Navigate to Directory #

drive.mount('/content/drive')

path = "/content/drive/MyDrive/DSO 574 assignment/3"

os.chdir(path)

MessageError: Error: credential propagation was unsuccessful

In [ ]:
netflix_data = pd.read_excel("./Ampere/Netflix catalogue USA 2016-2020.xlsx")
hulu_data = pd.read_excel("./Ampere/Hulu catalogue USA 2016-2020.xlsx")
amazon_data = pd.read_excel("./Ampere/Amazon Prime (excluding Amazon Other) catalogue USA 2016-2020.xlsx")

In [ ]:
reelgood_data = pd.read_csv("./Reelgood/Reel Good Data (Title+Service+Genre+Tag List).csv")

<ipython-input-5-c78d552ba611>:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  reelgood_data = pd.read_csv("./Reelgood/Reel Good Data (Title+Service+Genre+Tag List).csv")

#Nielsen Data

In [ ]:
share_data = pd.read_csv("./Nielsen/Share Data 2016 to 2020.csv")

<ipython-input-4-ee1e11c37e42>:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  share_data = pd.read_csv("./Share Data 2016 to 2020.csv")

In [ ]:
reach_data = pd.read_csv("./Nielsen/Reach Data 2016 to 2020.csv")

In [ ]:
share_data.head()

,Unnamed: 0,Coverage Area,Market Break,Demographic,Broadcast Date,Originator,Program Name,Telecast Report Start Time,Summary Type Code,Playback Period,...,Rating Base,MC Weighted Viewing AA Minutes,MC DTVR,PESS,Avg Intab,Avg Scaled Intab,Avg Scaled Installed,UE (000),UE Type,File
0,0,Total US,Composite,Persons 2 - 99,2017-01-01,ABC,AMER FUNN HOME VIDEOS,19:00:00,COMEDY VARIETY,Live+7 Days (+168 Hours) | TV with Digital | L...,...,3.016700e+08,3.775582e+08,"C,M",65696,100197,36246,39699,301670,S,USC Marshall 2017 v2S.xlsx
1,1,Total US,Composite,Persons 2 - 99,2017-01-01,ABC,CONVICTION,22:00:00,GENERAL DRAMA,Live+7 Days (+168 Hours) | TV with Digital | L...,...,3.016700e+08,2.405016e+08,"C,M",65696,100197,36246,39699,301670,S,USC Marshall 2017 v2S.xlsx
2,2,Total US,Composite,Persons 2 - 99,2017-01-01,AMC,WALKING DEAD MARATHON,19:10:00,GENERAL DRAMA,Live+7 Days (+168 Hours) | TV with Digital | L...,...,3.016700e+08,4.448191e+07,"C,M",65696,100197,36246,39699,301670,S,USC Marshall 2017 v2S.xlsx
3,3,Total US,Composite,Persons 2 - 99,2017-01-01,AMC,WALKING DEAD MARATHON,20:10:00,GENERAL DRAMA,Live+7 Days (+168 Hours) | TV with Digital | L...,...,3.016700e+08,6.965312e+07,"C,M",65696,100197,36246,39699,301670,S,USC Marshall 2017 v2S.xlsx
4,4,Total US,Composite,Persons 2 - 99,2017-01-01,AMC,WALKING DEAD MARATHON,21:35:00,GENERAL DRAMA,Live+7 Days (+168 Hours) | TV with Digital | L...,...,3.016700e+08,4.549348e+07,"C,M",65696,100197,36246,39699,301670,S,USC Marshall 2017 v2S.xlsx

In [ ]:
share_data['Coverage Area'].unique()

array(['Total US'], dtype=object)

In [ ]:
share_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267927 entries, 0 to 267926
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unnamed: 0                      267927 non-null  int64
 1   Coverage Area                   267927 non-null  object
 2   Market Break                    267927 non-null  object
 3   Demographic                     267927 non-null  object
 4   Broadcast Date                  267927 non-null  object
 5   Originator                      267927 non-null  object
 6   Program Name                    267927 non-null  object
 7   Telecast Report Start Time      267927 non-null  object
 8   Summary Type Code               267927 non-null  object
 9   Playback Period                 267927 non-null  object
 10  Total Duration                  267927 non-null  int64
 11  MC US AA %                      267927 non-null  float64
 12  MC US AA Proj (units)           267927 non-null  int64
 13  MC US Share AA %                267927 non-null  float64
 14  MC US HUT %                     267927 non-null  float64
 15  MC US HUT Proj (units)          267927 non-null  int64
 16  Rating Base                     267927 non-null  float64
 17  MC Weighted Viewing AA Minutes  267927 non-null  float64
 18  MC DTVR                         20079 non-null   object
 19  PESS                            267927 non-null  int64
 20  Avg Intab                       267927 non-null  int64
 21  Avg Scaled Intab                267927 non-null  int64
 22  Avg Scaled Installed            267927 non-null  int64
 23  UE (000)                        267927 non-null  int64
 24  UE Type                         267927 non-null  object
 25  File                            267927 non-null  object
dtypes: float64(5), int64(9), object(12)
memory usage: 53.1+ MB

In [ ]:
reach_data.head()

nielsen_data = reach_data

In [ ]:
nielsen_data.head()

,Unnamed: 0,Coverage Area,Market Break,Demographic,Schedule Name,Date,Originator,Program,Playback Period,Units,...,Qualified AA GRP%,Spot AA GRP Proj(units),Qualified AA GRP Proj(units),AA Effective Reach(3+),Weighted Intab,PESS,Unified Count,UE (000),UE/Proj Type,File
0,0,Total US,Composite,Persons 2 - 99,USC Marshall Reach 2018 v1,01/01/2018,COMEDY CENTRAL,CHAPPELLES SHOW,Live+7 Days (+168 Hours) | TV with Digital | L...,6,...,1.086498,68015665,3311940,0.143063,304499468,43551,73452,304827,S,USC Marshall Reach 2018 v1.xlsx
1,1,Total US,Composite,Persons 2 - 99,USC Marshall Reach 2018 v1,01/01/2018,AMC,BREAKING BAD MARATHON,Live+7 Days (+168 Hours) | TV with Digital | L...,2,...,0.386566,47466710,1178358,0.004686,304499468,43551,73452,304827,S,USC Marshall Reach 2018 v1.xlsx
2,2,Total US,Composite,Persons 2 - 99,USC Marshall Reach 2018 v1,01/01/2018,CBS,"BIG BANG THEORY, THE-1/1",Live+7 Days (+168 Hours) | TV with Digital | L...,1,...,2.116748,151299653,6452420,0.000407,304499468,43551,73452,304827,S,USC Marshall Reach 2018 v1.xlsx
3,3,Total US,Composite,Persons 2 - 99,USC Marshall Reach 2018 v1,01/01/2018,NBC,BETTER LATE THAN NEVER,Live+7 Days (+168 Hours) | TV with Digital | L...,1,...,2.137488,253579666,6515641,0.004577,304499468,43551,73452,304827,S,USC Marshall Reach 2018 v1.xlsx
4,4,Total US,Composite,Persons 2 - 99,USC Marshall Reach 2018 v1,01/01/2018,CBS,YOUNG SHELDON 830PM-SP,Live+7 Days (+168 Hours) | TV with Digital | L...,1,...,1.938229,147864817,5908244,0.000000,304499468,43551,73452,304827,S,USC Marshall Reach 2018 v1.xlsx

#
AA Average Frequency, = The average number of times households or persons viewed a given program, station, or advertisement during a specific time period, such as one month. This number is derived by dividing the Gross Rating Points (GRP) by the total non-duplicated audience (cume). For example, if a group of programs achieved 30 GRPs and a cume of 20, then the average frequency would be 1.5 exposures per person or household.

In [ ]:
nielsen_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174889 entries, 0 to 174888
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    174889 non-null  int64
 1   Coverage Area                 174889 non-null  object
 2   Market Break                  174889 non-null  object
 3   Demographic                   174889 non-null  object
 4   Schedule Name                 174889 non-null  object
 5   Date                          174889 non-null  object
 6   Originator                    174889 non-null  object
 7   Program                       174889 non-null  object
 8   Playback Period               174889 non-null  object
 9   Units                         174889 non-null  int64
 10  AA Reach%                     174889 non-null  float64
 11  AA Reach Proj(units)          174889 non-null  int64
 12  AA Average Frequency          174889 non-null  float64
 13  AA Average Minutes            174889 non-null  float64
 14  Spot AA GRP%                  174889 non-null  float64
 15  Qualified AA GRP%             174889 non-null  float64
 16  Spot AA GRP Proj(units)       174889 non-null  int64
 17  Qualified AA GRP Proj(units)  174889 non-null  int64
 18  AA Effective Reach(3+)        174889 non-null  float64
 19  Weighted Intab                174889 non-null  int64
 20  PESS                          174889 non-null  int64
 21  Unified Count                 174889 non-null  int64
 22  UE (000)                      174889 non-null  int64
 23  UE/Proj Type                  174889 non-null  object
 24  File                          174889 non-null  object
dtypes: float64(6), int64(9), object(10)
memory usage: 33.4+ MB

In [ ]:
nielsen_data.shape

(174889, 25)

In [ ]:
print(nielsen_data.isnull().sum())

Unnamed: 0                      0
Coverage Area                   0
Market Break                    0
Demographic                     0
Schedule Name                   0
Date                            0
Originator                      0
Program                         0
Playback Period                 0
Units                           0
AA Reach%                       0
AA Reach Proj(units)            0
AA Average Frequency            0
AA Average Minutes              0
Spot AA GRP%                    0
Qualified AA GRP%               0
Spot AA GRP Proj(units)         0
Qualified AA GRP Proj(units)    0
AA Effective Reach(3+)          0
Weighted Intab                  0
PESS                            0
Unified Count                   0
UE (000)                        0
UE/Proj Type                    0
File                            0
dtype: int64

In [ ]:
nielsen_data = nielsen_data.drop(columns=[
    'Unnamed: 0',
    'Playback Period',
    'File'
])

In [ ]:
import pandas as pd

# Convert 'Date' column to datetime dtype
nielsen_data['Date'] = pd.to_datetime(nielsen_data['Date'])

# Extract year, month, and day into separate columns
nielsen_data['Year'] = nielsen_data['Date'].dt.year
nielsen_data['Month'] = nielsen_data['Date'].dt.month
nielsen_data['Day'] = nielsen_data['Date'].dt.day

# Display the DataFrame with the new columns
print(nielsen_data.head())

  Coverage Area Market Break     Demographic                Schedule Name  \
0      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
1      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
2      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
3      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
4      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1

        Date        Originator                     Program  Units  AA Reach%  \
0 2018-01-01   COMEDY CENTRAL             CHAPPELLES SHOW       6   0.479660
1 2018-01-01              AMC       BREAKING BAD MARATHON       2   0.259126
2 2018-01-01              CBS    BIG BANG THEORY, THE-1/1       1   2.107874
3 2018-01-01              NBC      BETTER LATE THAN NEVER       1   2.038779
4 2018-01-01              CBS      YOUNG SHELDON 830PM-SP       1   1.930053

   AA Reach Proj(units)  ...  Qualified AA GRP Proj(units)  \
0               1462132  ...                       3311940
1                789885  ...                       1178358
2               6425370  ...                       6452420
3               6214748  ...                       6515641
4               5883323  ...                       5908244

   AA Effective Reach(3+)  Weighted Intab   PESS  Unified Count  UE (000)  \
0                0.143063       304499468  43551          73452    304827
1                0.004686       304499468  43551          73452    304827
2                0.000407       304499468  43551          73452    304827
3                0.004577       304499468  43551          73452    304827
4                0.000000       304499468  43551          73452    304827

   UE/Proj Type  Year  Month  Day
0             S  2018      1    1
1             S  2018      1    1
2             S  2018      1    1
3             S  2018      1    1
4             S  2018      1    1

[5 rows x 25 columns]

In [ ]:
# Get unique values of the "Year" column
unique_years = nielsen_data['Year'].unique()

# Print the unique values
print(unique_years)

[2018 2019 2016 2020 2017]

In [ ]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Display the DataFrame with all columns
print(nielsen_data.head())

  Coverage Area Market Break     Demographic                Schedule Name  \
0      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
1      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
2      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
3      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1
4      Total US    Composite  Persons 2 - 99  USC Marshall Reach 2018 v1

        Date        Originator                     Program  Units  AA Reach%  \
0 2018-01-01   COMEDY CENTRAL             CHAPPELLES SHOW       6   0.479660
1 2018-01-01              AMC       BREAKING BAD MARATHON       2   0.259126
2 2018-01-01              CBS    BIG BANG THEORY, THE-1/1       1   2.107874
3 2018-01-01              NBC      BETTER LATE THAN NEVER       1   2.038779
4 2018-01-01              CBS      YOUNG SHELDON 830PM-SP       1   1.930053

   AA Reach Proj(units)  AA Average Frequency  AA Average Minutes  \
0               1462132              2.265144           46.518141
1                789885              1.491810           60.093212
2               6425370              1.004210           23.547228
3               6214748              1.048416           40.802890
4               5883323              1.004236           25.132876

   Spot AA GRP%  Qualified AA GRP%  Spot AA GRP Proj(units)  \
0     22.312874           1.086498                 68015665
1     15.571688           0.386566                 47466710
2     49.634597           2.116748                151299653
3     83.188059           2.137488                253579666
4     48.507782           1.938229                147864817

   Qualified AA GRP Proj(units)  AA Effective Reach(3+)  Weighted Intab  \
0                       3311940                0.143063       304499468
1                       1178358                0.004686       304499468
2                       6452420                0.000407       304499468
3                       6515641                0.004577       304499468
4                       5908244                0.000000       304499468

    PESS  Unified Count  UE (000) UE/Proj Type  Year  Month  Day
0  43551          73452    304827            S  2018      1    1
1  43551          73452    304827            S  2018      1    1
2  43551          73452    304827            S  2018      1    1
3  43551          73452    304827            S  2018      1    1
4  43551          73452    304827            S  2018      1    1

In [ ]:
hulu_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331464 entries, 0 to 331463
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   YearMonth                   331464 non-null  object
 1   Platform                    331464 non-null  object
 2   Country                     331464 non-null  object
 3   Content Type                331464 non-null  object
 4   Title                       331464 non-null  object
 5   First Release Year          331464 non-null  object
 6   Primary Genre               331464 non-null  object
 7   SecondaryGenre              331464 non-null  object
 8   Genre                       331464 non-null  object
 9   Duration                    331464 non-null  object
 10  Duration Group              331464 non-null  object
 11  Number of Episodes          331464 non-null  object
 12  Primary Production Country  331464 non-null  object
 13  Primary Production Company  331460 non-null  object
dtypes: object(14)
memory usage: 35.4+ MB

In [ ]:
netflix_data.head()

,YearMonth,Platform,Country,Content Type,Title,First Release Year,Primary Genre,SecondaryGenre,Genre,Duration,Duration Group,Number of Episodes,Primary Production Country,Primary Production Company
0,Jan-2016,Netflix,USA,Movie,[rec] 3: Genesis,2012,Horror,Comedy,Horror - Comedy,80,60 - 90 minutes,-,Spain,Filmax
1,Jan-2016,Netflix,USA,Movie,[rec] 4: Apocalypse,2014,Horror,Action & Adventure,Horror - Action & Adventure,95,90 - 120 minutes,-,Spain,Entertainment One
2,Jan-2016,Netflix,USA,Movie,#chicagogirl: the Social Network Takes on a Di...,2015,Documentary,Political,Documentary - Political,73,60 - 90 minutes,-,USA,Revolutio
3,Jan-2016,Netflix,USA,TVSeason,#deathtoselfie With Steven Furtick: Season 1,2014,Miscellaneous,Miscellaneous,Miscellaneous - Miscellaneous,520,45 - 60 minutes,10,USA,No Company Assigned
4,Jan-2016,Netflix,USA,Movie,1 Chance 2 Dance,2014,Romance,Drama,Romance - Drama,85,60 - 90 minutes,-,USA,DAVED Productions

In [ ]:
# Data cleaning for Netflix data
netflix_data['YearMonth'] = pd.to_datetime(netflix_data['YearMonth'], format='%b-%Y')
netflix_data['First Release Year'] = pd.to_datetime(netflix_data['First Release Year'], errors='coerce')
netflix_data['Duration'] = pd.to_numeric(netflix_data['Duration'], errors='coerce')
netflix_data['Number of Episodes'] = pd.to_numeric(netflix_data['Number of Episodes'], errors='coerce')

# Data cleaning for Nielsen data
nielsen_data['Date'] = pd.to_datetime(nielsen_data['Date'])

# Aggregation for Netflix data
netflix_aggregated = netflix_data.groupby(['Country', 'Primary Genre']).agg({'Title': 'count', 'Duration': 'mean'}).reset_index()

# Aggregation for Nielsen data
nielsen_aggregated = nielsen_data.groupby(['Coverage Area', 'Demographic']).agg({'Units': 'sum', 'AA Reach%': 'mean'}).reset_index()

# Analysis (example analysis, customize as per requirement)
# Top genres on Netflix by country
top_genres_by_country = netflix_aggregated.sort_values(by='Title', ascending=False).groupby('Country').head(1)

# Average duration of content by genre
average_duration_by_genre = netflix_data.groupby('Primary Genre')['Duration'].mean().reset_index()

#Only with reelgood

In [ ]:
reelgood_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287834 entries, 0 to 287833
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             287834 non-null  int64
 1   Title                  287834 non-null  object
 2   URL                    287834 non-null  object
 3   Type                   287834 non-null  object
 4   Service                287834 non-null  object
 5   Genre                  287834 non-null  object
 6   Tag                    287834 non-null  object
 7   IMDB                   283312 non-null  float64
 8   ReelGood               286904 non-null  float64
 9   AgeRating              166197 non-null  object
 10  Rated                  97564 non-null   object
 11  Released Year          287834 non-null  int64
 12  Duration Year          23071 non-null   object
 13  Seasons                23047 non-null   float64
 14  What it's about        148046 non-null  object
 15  Where to Watch         134161 non-null  object
 16  Rent or Buy Available  287834 non-null  int64
 17  Exclusive Service      287834 non-null  int64
 18  Has Tag                287834 non-null  int64
dtypes: float64(3), int64(5), object(11)
memory usage: 41.7+ MB

In [ ]:
reelgood_data.head()

,Unnamed: 0,Title,URL,Type,Service,Genre,Tag,IMDB,ReelGood,AgeRating,Rated,Released Year,Duration Year,Seasons,What it's about,Where to Watch,Rent or Buy Available,Exclusive Service,Has Tag
0,0,Breaking Bad,/show/breaking-bad-2008,tv,netflix,Crime,"['Drug', 'Doctor', 'Teacher', 'Gangster', 'Hig...",9.5,100.0,18+,TV-MA,2008,2008-2020,5.0,"When Walter White, a New Mexico chemistry teac...",62 episodes (100%) are available to stream on ...,1,0,1
1,1,Breaking Bad,/show/breaking-bad-2008,tv,netflix,Drama,"['Drug', 'Doctor', 'Teacher', 'Gangster', 'Hig...",9.5,100.0,18+,TV-MA,2008,2008-2020,5.0,"When Walter White, a New Mexico chemistry teac...",62 episodes (100%) are available to stream on ...,1,0,1
2,2,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Drama,"['War', 'Royalty', 'Political', 'Based on Book...",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,Seven noble families fight for control of the ...,74 episodes (100%) are available to stream on ...,1,0,1
3,3,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Action & Adventure,"['War', 'Royalty', 'Political', 'Based on Book...",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,Seven noble families fight for control of the ...,74 episodes (100%) are available to stream on ...,1,0,1
4,4,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Fantasy,"['War', 'Royalty', 'Political', 'Based on Book...",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,Seven noble families fight for control of the ...,74 episodes (100%) are available to stream on ...,1,0,1

In [ ]:
reelgood_data['Service'].unique()

array(['netflix', 'hbo_max', 'hbo', 'free', 'hulu_plus', 'fubo_tv',
       'hoopla', 'adult_swim_tveverywhere', 'adult_swim',
       'fx_tveverywhere', 'amazon_prime', 'cbs_all_access', 'philo',
       'comedycentral_tveverywhere', 'comedy', 'southpark', 'tbs',
       'crunchyroll_premium', 'funimation', 'tubi_tv', 'crunchyroll_free',
       'thecw', 'tnt', 'amc_premiere', 'amc', 'peacock',
       'nbc_tveverywhere', 'nbc', 'peacock_free', 'disney_plus', 'fox',
       'showtime', 'showtime_free', 'imdb_tv', 'youtube_premium',
       'youtube_premium_free', 'abc_tveverywhere', 'viceland_tve',
       'fox_tveverywhere', 'crackle', 'cw_seed', 'starz', 'disneynow',
       'disneynow_free', 'abc', 'syfy_tveverywhere', 'nbc_universo',
       'pbs', 'bbc_america_tve', 'apple_tv_plus', 'paramount_network_tve',
       'cartoon_network', 'cartoon_network_free', 'britbox', 'plex_free',
       'sundancenow', 'abc_news', 'dc_universe', 'natgeo',
       'freeform_free', 'Rent or Buy', 'plutotv', 'vudu_free', 'acorntv',
       'cbs', 'cinemax', 'comedycentralstandupplus', 'usa_tveverywhere',
       'logo_tve', 'abc_family', 'pop', 'usa', 'tvland',
       'tvland_tveverywhere', 'ifc', 'velocity_go', 'moto',
       'mtv_tveverywhere', 'hallmark_movies_now', 'dove', 'upfa',
       'oxygen_tveverywhere', 'syfy', 'epix', 'shudder',
       'history_tveverywhere', 'history', 'science_go', 'discovery_go',
       'mtv', 'cmt_tve', 'vh1_tveverywhere', 'lifetime', 'vh1',
       'sundance_tveverywhere', 'pbs_kids', 'watch_travel_channel',
       'travel', 'dest', 'best', 'natgeo_tveverywhere',
       'bet_tveverywhere', 'trutv_tveverywhere', 'wwe_network', 'hist',
       'smit', 'watchdisneyxd_tveverywhere', 'watch_food_network',
       'bravo_tveverywhere', 'bet_plus', 'ae_tveverywhere', 'spike',
       'hallmark_everywhere', 'cont', 'watchdisney', 'ae',
       'lifetime_tveverywhere', 'true', 'teamcoco', 'food_network',
       'telemundo_now', 'tlc_go', 'destination_america_go',
       'investigation_discovery_go', 'fyi_tveverywhere', 'fyi',
       'funny_or_die', 'nbc_news', 'nbc_news_tveverywhere',
       'shoutfactorytv', 'hgtv', 'watch_hgtv', 'mhzc', 'curiositystream',
       'animal_planet_go', 'spike_tveverywhere', 'cnbc_tveverywhere',
       'cnbc', '60_minutes_all_access', 'cbs_', 'indieflix', 'bet',
       'watchdisneyxd', 'shout_factory_tv', 'nickjr', 'revry',
       'watchdisneyjr', 'watchdisneyjr_tveverywhere', 'cmt', 'vimeo',
       'logo', 'discovery_life_go', 'xive', 'ameb', 'here',
       'we_tveverywhere', 'docu', 'smithsonian', 'diy',
       'watch_diy_network', 'urbanmoviechannel', 'gaia', 'viceland_free',
       'viewster', 'tlc', 'bounce_tv', 'fuse_tv', 'watch_cooking_channel',
       'ahc_go', 'collegehumor', 'natgeo_kids_free', 'disney_junior',
       'sprout_now', 'oxygen', 'come', 'kanopy', 'criterion_channel',
       'popcornflix', 'hiya', 'mons', 'warr', 'fandor', 'dox', 'secr',
       'cine', 'qell', 'indi', 'full', 'watch_tcm', 'trib', 'youtube',
       'dari', 'mubi', 'fear', 'film', 'amazon_prime_free', 'scre',
       'docc', 'real', 'life', 'investigation_discovery', 'spac'],
      dtype=object)

##To analyze the top IMDB-rated genre for each service in the provided reelgood_data

In [ ]:
reelgood_data.dropna(subset=['Service', 'Genre'], inplace=True)

In [ ]:
reelgood_data.dropna(subset=['IMDB'], inplace=True)

# Group by 'Service' and 'Genre', calculate the average IMDB rating for each combination
service_genre_avg_imdb = reelgood_data.groupby(['Service', 'Genre'])['IMDB'].mean().reset_index()

# Find the index of the maximum IMDB rating for each service
max_imdb_index = service_genre_avg_imdb.groupby('Service')['IMDB'].idxmax()

# Extract the rows with maximum IMDB rating for each service
top_genre_per_service = service_genre_avg_imdb.loc[max_imdb_index]

print(top_genre_per_service)

                    Service               Genre      IMDB
0     60_minutes_all_access         Documentary  7.400000
9               Rent or Buy         Documentary  7.122392
39                      abc       Home & Garden  7.900000
64               abc_family               Sport  7.500000
67                 abc_news  Action & Adventure  8.400000
...                     ...                 ...       ...
2562            wwe_network         Documentary  7.800000
2573                   xive             Reality  8.000000
2579                youtube             Fantasy  8.000000
2591        youtube_premium           Game Show  9.200000
2604   youtube_premium_free         Documentary  8.666667

[201 rows x 3 columns]

In [ ]:
# Filter for specific services
services_of_interest = ['netflix', 'hbo_max', 'hbo', 'hulu_plus', 'peacock', 'amazon_prime', 'disney_plus', 'fox']
reelgood_data_filtered = reelgood_data[reelgood_data['Service'].isin(services_of_interest)]

# Drop rows with NaN values in 'IMDB' column
reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

# Group by 'Service' and 'Genre', calculate the average IMDB rating for each combination
service_genre_avg_imdb = reelgood_data_filtered.groupby(['Service', 'Genre'])['IMDB'].mean().reset_index()

# Find the index of the maximum IMDB rating for each service
max_imdb_index = service_genre_avg_imdb.groupby('Service')['IMDB'].idxmax()

# Extract the rows with maximum IMDB rating for each service
top_genre_per_service = service_genre_avg_imdb.loc[max_imdb_index]

print(top_genre_per_service)

          Service            Genre      IMDB
27   amazon_prime           Travel  7.303226
51    disney_plus           Travel  7.875000
66            fox  Science-Fiction  8.600000
84            hbo            LGBTQ  7.430000
120       hbo_max           Travel  8.350000
148     hulu_plus           Travel  7.595652
176       netflix           Travel  7.444444
197       peacock            Sport  7.950000

<ipython-input-16-265cc0110323>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

##find the genre that frequently occurs with high IMDB ratings for each service, you can count the occurrences of each genre for each service and then select the genre with the highest count of high IMDB ratings.

In [ ]:
# Filter for specific services
services_of_interest = ['netflix', 'hbo_max', 'hbo', 'hulu_plus', 'peacock', 'amazon_prime', 'disney_plus', 'fox']
reelgood_data_filtered = reelgood_data[reelgood_data['Service'].isin(services_of_interest)]

# Drop rows with NaN values in 'IMDB' column
reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

# Define a threshold for high IMDB ratings
imdb_threshold = 8.0

# Filter for rows with IMDB ratings above the threshold
high_imdb_data = reelgood_data_filtered[reelgood_data_filtered['IMDB'] > imdb_threshold]

# Group by 'Service' and 'Genre', and count occurrences of high IMDB ratings for each genre
genre_imdb_counts = high_imdb_data.groupby(['Service', 'Genre']).size().reset_index(name='Count')

# Find the genre with the highest count of high IMDB ratings for each service
max_count_indices = genre_imdb_counts.groupby('Service')['Count'].idxmax()
top_genre_per_service = genre_imdb_counts.loc[max_count_indices]

print(top_genre_per_service)

          Service               Genre  Count
8    amazon_prime         Documentary    336
28    disney_plus  Action & Adventure     32
47            fox         Documentary      4
61            hbo               Drama     78
85        hbo_max               Drama    152
110     hulu_plus               Drama    108
137       netflix               Drama    216
160       peacock               Drama      7

<ipython-input-18-b0012e31e56e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

## find the genre that occurs most frequently with low IMDB ratings for each service, you can count the occurrences of each genre for each service and then select the genre with the highest count of low IMDB ratings.

In [ ]:
# Filter for specific services
services_of_interest = ['netflix', 'hbo_max', 'hbo', 'hulu_plus', 'peacock', 'amazon_prime', 'disney_plus', 'fox']
reelgood_data_filtered = reelgood_data[reelgood_data['Service'].isin(services_of_interest)]

# Drop rows with NaN values in 'IMDB' column
reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

# Define a threshold for low IMDB ratings
imdb_threshold = 5.0

# Filter for rows with IMDB ratings below the threshold
low_imdb_data = reelgood_data_filtered[reelgood_data_filtered['IMDB'] < imdb_threshold]

# Group by 'Service' and 'Genre', and count occurrences of low IMDB ratings for each genre
genre_imdb_counts = low_imdb_data.groupby(['Service', 'Genre']).size().reset_index(name='Count')

# Find the genre with the highest count of low IMDB ratings for each service
max_count_indices = genre_imdb_counts.groupby('Service')['Count'].idxmax()
top_genre_per_service = genre_imdb_counts.loc[max_count_indices]

print(top_genre_per_service)

          Service    Genre  Count
16   amazon_prime   Horror   1136
35    disney_plus   Family     44
40            fox  Reality      3
45            hbo   Comedy     46
65        hbo_max   Comedy     56
88      hulu_plus   Comedy     56
112       netflix   Comedy    213
141       peacock  Reality     11

<ipython-input-19-c3332563afd5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reelgood_data_filtered.dropna(subset=['IMDB'], inplace=True)

In [ ]:

# Filter data for HBO Max service
hbo_max_data = reelgood_data[reelgood_data['Service'] == 'hbo_max']

# Extract unique genres present in HBO Max content
hbo_max_genres = hbo_max_data['Genre'].unique()

# Print the genres present in HBO Max content
print("Genres Present in HBO Max Content:")
print(hbo_max_genres)

Genres Present in HBO Max Content:
['Drama' 'Action & Adventure' 'Fantasy' 'Comedy' 'Science-Fiction'
 'Animation' 'History' 'Romance' 'Crime' 'Thriller' 'Mystery' 'Anime'
 'Children' 'LGBTQ' 'Family' 'Horror' 'Documentary' 'Musical' 'Sport'
 'Reality' 'Game Show' 'Biography' 'Travel' 'Food' 'Home & Garden'
 'Stand-up & Talk' 'Cult' 'Independent']

In [ ]:
# Filter data for Netflix
netflix_data = reelgood_data[reelgood_data['Service'] == 'netflix']

# Extract unique genres present in HBO Max content
netflix_genres = netflix_data['Genre'].unique()

# Print the genres present in HBO Max content
print("Genres Present in Netflix:")
print(netflix_genres)

Genres Present in Netflix:
['Crime' 'Drama' 'Fantasy' 'Horror' 'Action & Adventure' 'Family'
 'Animation' 'Anime' 'Mystery' 'Comedy' 'Science-Fiction' 'Thriller'
 'LGBTQ' 'Biography' 'History' 'Documentary' 'Sport' 'Romance' 'Cult'
 'Reality' 'Children' 'Musical' 'Food' 'Game Show' 'Travel'
 'Stand-up & Talk' 'Home & Garden' 'Independent']

In [ ]:
# Sort Netflix data by IMDb ratings in descending order
top_rated_netflix = reelgood_data[reelgood_data['Service'] == 'netflix'].sort_values(by='IMDB', ascending=False)

# Print the top-rated Netflix content
print("Top Rated Content on Netflix:")
print(top_rated_netflix.head(5))

Top Rated Content on Netflix:
      Unnamed: 0         Title                      URL Type  Service  \
0              0  Breaking Bad  /show/breaking-bad-2008   tv  netflix
1              1  Breaking Bad  /show/breaking-bad-2008   tv  netflix
1257        1257    Our Planet    /show/our-planet-2019   tv  netflix
7376        7376       Ramayan       /show/ramayan-1987   tv  netflix
7375        7375       Ramayan       /show/ramayan-1987   tv  netflix

                   Genre                                                Tag  \
0                  Crime  ['Drug', 'Doctor', 'Teacher', 'Gangster', 'Hig...
1                  Drama  ['Drug', 'Doctor', 'Teacher', 'Gangster', 'Hig...
1257         Documentary                                         ['Animal']
7376             Fantasy                                              [nan]
7375  Action & Adventure                                              [nan]

      IMDB  ReelGood AgeRating  Rated  Released Year Duration Year  Seasons  \
0      9.5     100.0       18+  TV-MA           2008     2008-2020      5.0
1      9.5     100.0       18+  TV-MA           2008     2008-2020      5.0
1257   9.3      84.0        7+  TV-PG           2019     2019-2020      1.0
7376   9.2      68.0       all    NaN           1987           NaN      NaN
7375   9.2      68.0       all    NaN           1987           NaN      NaN

                                        What it's about  \
0     When Walter White, a New Mexico chemistry teac...
1     When Walter White, a New Mexico chemistry teac...
1257  Experience our planet's natural beauty and exa...
7376                                                NaN
7375                                                NaN

                                         Where to Watch  \
0     62 episodes (100%) are available to stream on ...
1     62 episodes (100%) are available to stream on ...
1257  8 episodes (100%) are available to stream on a...
7376                                                NaN
7375                                                NaN

      Rent or Buy Available  Exclusive Service  Has Tag
0                         1                  0        1
1                         1                  0        1
1257                      0                  1        1
7376                      1                  0        0
7375                      1                  0        0

In [ ]:
reelgood_data.shape

(287834, 19)

In [ ]:
# Remove duplicates based on the "Title" column
unique_data = reelgood_data.drop_duplicates(subset='Title')

# Print the shape of the unique dataset to compare with the original dataset
print("Shape of unique dataset:", unique_data.shape)

Shape of unique dataset: (61959, 19)

In [ ]:
# Sort Netflix data by IMDb ratings in descending order
top_rated_netflix = unique_data[unique_data['Service'] == 'netflix'].sort_values(by='IMDB', ascending=False)

# Print the top-rated Netflix content
print("Top Rated Content on Netflix:")
print(top_rated_netflix.head(5))

Top Rated Content on Netflix:
      Unnamed: 0                       Title  \
0              0                Breaking Bad
1257        1257                  Our Planet
5318        5318             Yeh Meri Family
54            54  Avatar: The Last Airbender
7374        7374                     Ramayan

                                       URL Type  Service        Genre  \
0                  /show/breaking-bad-2008   tv  netflix        Crime
1257                 /show/our-planet-2019   tv  netflix  Documentary
5318            /show/yeh-meri-family-2018   tv  netflix      Musical
54    /show/avatar-the-last-airbender-2005   tv  netflix       Family
7374                    /show/ramayan-1987   tv  netflix        Drama

                                                    Tag  IMDB  ReelGood  \
0     ['Drug', 'Doctor', 'Teacher', 'Gangster', 'Hig...   9.5     100.0
1257                                         ['Animal']   9.3      84.0
5318                                        ['Singing']   9.2      72.0
54    ['Magic', 'Martial Arts', 'Religion', 'Friends...   9.2      94.0
7374                                              [nan]   9.2      68.0

     AgeRating  Rated  Released Year Duration Year  Seasons  \
0          18+  TV-MA           2008     2008-2020      5.0
1257        7+  TV-PG           2019     2019-2020      1.0
5318       NaN    NaN           2018     2018-2020      1.0
54          7+  TV-PG           2005     2005-2020      3.0
7374       all    NaN           1987           NaN      NaN

                                        What it's about  \
0     When Walter White, a New Mexico chemistry teac...
1257  Experience our planet's natural beauty and exa...
5318  Set in the summer of 1998 it is a story about ...
54    In a war-torn world of elemental magic, a youn...
7374                                                NaN

                                         Where to Watch  \
0     62 episodes (100%) are available to stream on ...
1257  8 episodes (100%) are available to stream on a...
5318  7 episodes (100%) are available to stream on a...
54    65 episodes (98%) are available to stream on a...
7374                                                NaN

      Rent or Buy Available  Exclusive Service  Has Tag
0                         1                  0        1
1257                      0                  1        1
5318                      0                  1        1
54                        1                  0        1
7374                      1                  0        0

#Bonus

In [ ]:
# Set the display options to show more characters per column
pd.set_option('display.max_colwidth', None)

# Display the DataFrame with the entire "Platform" column visible
print(reelgood_data[['Where to Watch']])

                                                                                                                                                                                                  Where to Watch
0             62 episodes (100%) are available to stream on a popular subscription service (Netflix). 62 episodes (100%) are available to rent or buy from $1.99 on 5 services (iTunes, Google Play & 3 others).
1             62 episodes (100%) are available to stream on a popular subscription service (Netflix). 62 episodes (100%) are available to rent or buy from $1.99 on 5 services (iTunes, Google Play & 3 others).
2       74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).
3       74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).
4       74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).
...                                                                                                                                                                                                          ...
287829                                                                                                                                                                                                       NaN
287830                                                                                                                                                                                                       NaN
287831                                                                                                                                                                                                       NaN
287832                                                                                                                                                                                                       NaN
287833                                                                                                                                                                                                       NaN

[287834 rows x 1 columns]

In [ ]:
reelgood_data

,Unnamed: 0,Title,URL,Type,Service,Genre,Tag,IMDB,ReelGood,AgeRating,Rated,Released Year,Duration Year,Seasons,What it's about,Where to Watch,Rent or Buy Available,Exclusive Service,Has Tag
0,0,Breaking Bad,/show/breaking-bad-2008,tv,netflix,Crime,"['Drug', 'Doctor', 'Teacher', 'Gangster', 'High School']",9.5,100.0,18+,TV-MA,2008,2008-2020,5.0,"When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime","62 episodes (100%) are available to stream on a popular subscription service (Netflix). 62 episodes (100%) are available to rent or buy from $1.99 on 5 services (iTunes, Google Play & 3 others).",1,0,1
1,1,Breaking Bad,/show/breaking-bad-2008,tv,netflix,Drama,"['Drug', 'Doctor', 'Teacher', 'Gangster', 'High School']",9.5,100.0,18+,TV-MA,2008,2008-2020,5.0,"When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime","62 episodes (100%) are available to stream on a popular subscription service (Netflix). 62 episodes (100%) are available to rent or buy from $1.99 on 5 services (iTunes, Google Play & 3 others).",1,0,1
2,2,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Drama,"['War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal', 'War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal']",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond","74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).",1,0,1
3,3,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Action & Adventure,"['War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal', 'War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal']",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond","74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).",1,0,1
4,4,Game of Thrones,/show/game-of-thrones-2011,tv,hbo_max,Fantasy,"['War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal', 'War', 'Royalty', 'Political', 'Based on Books', 'Adaptation', 'Animal']",9.3,98.0,18+,TV-MA,2011,2011-2020,8.0,"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond","74 episodes (100%) are available to stream on a popular subscription service (HBO MAX & HBO). 74 episodes (100%) are available to rent or buy from $1.99 on 6 services (iTunes, Google Play & 4 others).",1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287829,287829,Antes de Morir,/movie/antes-de-morir-2000,movies,plutotv,Drama,"[nan, nan, nan, nan]",NaN,12.0,13+,NaN,2000,NaN,NaN,NaN,NaN,0,0,0
287830,287830,Kurdish Factor: The Untold Story Of The Gulf Wars,/movie/kurdish-factor-the-untold-story-of-the-gulf-wars-2018,movies,amazon_prime,Documentary,[nan],NaN,NaN,NaN,NaN,2018,NaN,NaN,NaN,NaN,1,0,0
287831,287831,Latex - Fetish or Fashion?,/movie/latex-fetish-or-fashion-2017-1,movies,hoopla,Documentary,[nan],NaN,12.0,NaN,NaN,2017,NaN,NaN,NaN,NaN,0,1,0
287832,287832,Macbeth,/movie/macbeth-1997-1,movies,hoopla,Drama,[nan],NaN,10.0,NaN,NaN,1997,NaN,NaN,NaN,NaN,0,1,0
287833,287833,Viva la Causa,/movie/viva-la-causa-1974,movies,fandor,Documentary,[nan],NaN,NaN,NaN,NaN,1974,NaN,NaN,NaN,NaN,0,1,0

In [ ]:
def recommend_based_on_input(input_text, reelgood_data):
    # Convert input text to lowercase for case-insensitive matching
    input_text = input_text.lower()

    # Filter the DataFrame based on the input text
    filtered_data = reelgood_data[reelgood_data['Title'].str.lower().str.contains(input_text) |
                         reelgood_data['Genre'].str.lower().str.contains(input_text)]


    filtered_data = filtered_data.sort_values(by='IMDB', ascending=False)


    recommendations = filtered_data.head(5)[['Title', 'IMDB', 'ReelGood']]

    return recommendations


user_input = input("Please provide a genre of movies or shows you like: ")

recommendations = recommend_based_on_input(user_input, reelgood_data)

if recommendations.empty:
    print("Sorry, no recommendations found based on your input.")
else:
    print("Recommendations based on your input:")
    print(recommendations)

Please provide a genre of movies or shows you like: comedy
Recommendations based on your input:
                                          Title  IMDB  ReelGood
11787                              Malgudi Days   9.5      63.0
15240     The Last Drive-in With Joe Bob Briggs   9.5      59.0
9                                Rick and Morty   9.2      96.0
13                               Rick and Morty   9.2      96.0
153490  Steven Banks: Home Entertainment Center   9.2      50.0

#Rank the recommendations by both IMDB rating and ReelGood rating,

In [ ]:
def recommend_based_on_input(input_text, reelgood_data):
    # Convert input text to lowercase for case-insensitive matching
    input_text = input_text.lower()


    filtered_data = reelgood_data[reelgood_data['Title'].str.lower().str.contains(input_text) |
                                  reelgood_data['Genre'].str.lower().str.contains(input_text)]


    filtered_data = filtered_data.sort_values(by=['IMDB', 'ReelGood'], ascending=[False, False])

    filtered_data = filtered_data.drop_duplicates(subset='Title')


    filtered_data = filtered_data.dropna(subset=["What it's about", 'Where to Watch'])


    recommendations = filtered_data.head(5)[['Title', 'IMDB', 'ReelGood', "What it's about", 'Where to Watch']]

    return recommendations


user_input = input("Please provide a genre of movies or shows you like: ")

recommendations = recommend_based_on_input(user_input, reelgood_data)

if recommendations.empty:
    print("Sorry, no recommendations found based on your input.")
else:
    print("Recommendations based on your input:")
    print(recommendations)

Please provide a genre of movies or shows you like: comedy
Recommendations based on your input:
                          Title  IMDB  ReelGood  \
9                Rick and Morty   9.2      96.0
5321            Yeh Meri Family   9.2      72.0
95386           Love on a Leash   9.2      64.0
3742   It's Okay to Not Be Okay   9.0      75.0
9406                 Reply 1988   9.0      67.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                      What it's about  \
9                                                                                           Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school
5321                                                                                                                                                                                                                                                                                                                                     Set in the summer of 1998 it is a story about conflicting emotions towards family members from the eyes of a twelve year old
95386                                                                                                                                                                                                                                                                                                                                                   A dog who strives to become a man seeks a woman who will love him enough for the transformation to take place
3742                                                                                                                                                                                                                             Desperate to escape from his emotional baggage and the heavy responsibility he’s had all his life, a psychiatric ward worker begins to heal with help from the unexpected—a woman who writes fairy tales but doesn’t believe in them
9406   There are five families living in the same neighbourhood of Ssangmundong, Dobong District, Northern Seoul. The neighbourhood is filled with warmth and love because everyone shares and cares for each other. Being the second daughter in the family with an elder sister and a younger brother, Sung Deok Sun often feels that she is being neglected by her parents. She finds out later that family is her only source of support when she is being harmed

                                                                                                                                                                                                                                                                                                                                                                     Where to Watch
9      5 episodes (12%) are available to watch free online (Adult Swim). 32 episodes (76%) are available to stream on a popular subscription service (HBO MAX, Hulu, fuboTV & 1 other). 5 episodes (12%) are available to stream on a TV everywhere service (Adult Swim). 41 episodes (98%) are available to rent or buy from $1.99 on 5 services (iTunes, Google Play & 3 others).
5321                                                                                                                                                                                                                                                                                         7 episodes (100%) are available to stream on a popular subscription service (Netflix).
95386                                                                                                                                                                                                                                                                                                                                        Available to watch free online (Tubi).
3742                                                                                                                                                                                                                                                                                        16 episodes (100%) are available to stream on a popular subscription service (Netflix).
9406                                                                                                                                                                                                                                                                                        42 episodes (100%) are available to stream on a popular subscription service (Netflix).